name: Docker Image CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.14

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set platforms
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64/v8
          
      - name: Build the Docker image
        run: |
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} crpi-p4epj17i9dug3hn9.cn-shanghai.personal.cr.aliyuncs.com
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag crpi-p4epj17i9dug3hn9.cn-shanghai.personal.cr.aliyuncs.com/test_r1/r1_java:0.0.1
          # 推送镜像到镜像仓库
          docker push crpi-p4epj17i9dug3hn9.cn-shanghai.personal.cr.aliyuncs.com/test_r1/r1_java:0.0.1
