name: Docker Image CI to ACR
 
on:
  push:
    branches: [ "main" ]  # 或者你希望触发构建的分支
  pull_request:
    branches: [ "main" ]
 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Aliyun Container Registry (ACR)
      uses: docker/login-action@v1 
      with:
        registry: crpi-p4epj17i9dug3hn9.cn-shanghai.personal.cr.aliyuncs.com  # 替换为你的 ACR 地址
        username: ${{ secrets.DOCKER_USERNAME }}  # 替换为你的阿里云账号名或RAM用户的AccessKey ID
        password: ${{ secrets.DOCKER_PASSWORD }}  # 替换为你的RAM用户的AccessKey Secret
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: crpi-p4epj17i9dug3hn9.cn-shanghai.personal.cr.aliyuncs.com/test_r1/r1_java:latest  # 替换为你的 ACR 地址和仓库信息
        platforms: linux/arm64
